# -*- coding: utf-8 -*-
"""data_loader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QozUw0U63QnAgjqms0SK0_n2Clg9rJ4a
"""

import numpy as np
import pandas as pd
import yfinance as yf

num_steps = 30
K = 1.0            # strike price ATM
brokerage_fee = 0.001

# Train, validation, and test splits
SPLITS = {
    "train": ("2006-01-01", "2019-12-31"),
    "val":   ("2020-01-01", "2021-12-31"),
    "test":  ("2022-01-01", "2025-12-31"),
}

def download_data():
    tickers = ['SPY', 'QQQ', 'DIA', 'IWM', 'XLK', 'XLF', 'XLV', 'XLE', 'XLP', 'EEM']
    price_data = yf.download(tickers, start="2006-01-01", end="2025-12-31", auto_adjust=False)['Open']
    price_data = price_data[sorted(tickers)]

    if price_data.isna().sum().sum() > 0:
        price_data = price_data.ffill().bfill()
    return price_data

def build_windows(price_data, start, end, n_steps=num_steps, stride=1):
    """Sliding windows of n_steps+1 prices, normalized so S_0 = 1.

    Windows never straddle a split boundary, so no purge gap is needed.
    Returns (paths, meta) where meta records ticker and start date.
    """
    seg = price_data.loc[start:end]
    w = n_steps + 1
    paths, meta = [], []

    for j, ticker in enumerate(seg.columns):
        s = seg.iloc[:, j].to_numpy()
        assert not np.isnan(s).any(), f"NaNs in {ticker} — resolve at panel level"
        dates = seg.index

        for d in range(0, len(s) - w + 1, stride):
            win = s[d:d + w]
            paths.append(win / win[0])
            meta.append((ticker, dates[d]))

    return (np.array(paths, dtype="float32"),
            pd.DataFrame(meta, columns=["ticker", "start_date"]))