# -*- coding: utf-8 -*-
"""metrics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mlONtxcol17Pox9Emh7BXjZN-6efHTDM
"""

import tensorflow as tf #[cite: 1]
import numpy as np #[cite: 1]

def entropic_loss(pnl, risk_aversion):
  """
  Entropic risk measure  rho(X) = (1/lambda) log E[exp(-lambda X)].

  pnl: terminal P&L, gains positive. Returns a positive number = risk.
  Also equals the exponential-utility indifference price of the payoff.
  """
  pnl = tf.reshape(tf.cast(pnl, tf.float32), [-1])

  # N is the mini-batch dimension
  N = tf.cast(tf.size(pnl), tf.float32)

  # reduce_logsumexp internally applies the same max-shift trick you'd do by hand
  log_mean_exp = tf.reduce_logsumexp(-risk_aversion * pnl) - tf.math.log(N)

  loss_val = (1.0 / risk_aversion) * log_mean_exp

  return loss_val

def calculate_cvar(pnl, alpha=0.95):
    """Average P&L in the worst (1 - alpha) tail. Reported as a positive loss number,
    like entropic loss, so higher = worse for both columns in the table below."""
    threshold = np.percentile(pnl, (1 - alpha) * 100)
    tail = pnl[pnl <= threshold]
    return -float(np.mean(tail))


def sweep_metrics(pnl, risk_aversion, deltas=None):
    row = {
        "mean": float(np.mean(pnl)),
        "std": float(np.std(pnl)),
        "entropic": float(entropic_loss(pnl, risk_aversion)),
        "cvar95": calculate_cvar(pnl),
    }
    if deltas is not None and deltas.shape[1] > 1:
        delta_prev = np.concatenate([np.zeros((deltas.shape[0], 1)), deltas[:, :-1]], axis=1)
        row["turnover"] = float(np.mean(np.sum(np.abs(deltas - delta_prev), axis=1)))
    else:
        row["turnover"] = 0.0
    return row