# -*- coding: utf-8 -*-
"""models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qQT2XCfscTt_4VPmnWQ8wYKSNBlhHG44
"""

import tensorflow as tf
from tensorflow import keras
import sklearn as sk

def mlp_features(x):
    delta_prev = x[:, 0:1]
    S          = x[:, 1:2]
    tau        = x[:, 2:3]
    m = tf.math.log(S / K)
    return tf.concat([delta_prev, m, tau], axis=1)


def rnn_features(x):
    """Shared by GRU and LSTM: their hidden state replaces delta_prev as
    the memory carrier, so only (S, tau) need to be fed in."""
    S   = x[..., 0:1]
    tau = x[..., 1:2]
    m = tf.math.log(S / K)
    return tf.concat([m, tau], axis=-1)



def make_mlp(width):
    return keras.Sequential([
        keras.Input(shape=(3,)),
        keras.layers.Lambda(mlp_features),
        keras.layers.Dense(width, activation="relu"),
        keras.layers.Dense(width, activation="relu"),
        keras.layers.Dense(1, activation="sigmoid"),
    ])


def make_gru(width):
    return keras.Sequential([
        keras.Input(shape=(num_steps, 2)),
        keras.layers.Lambda(rnn_features),
        keras.layers.GRU(width, return_sequences=True),
        keras.layers.Dense(1, activation="sigmoid"),
    ])


def make_lstm(width):
    return keras.Sequential([
        keras.Input(shape=(num_steps, 2)),
        keras.layers.Lambda(rnn_features),
        keras.layers.LSTM(width, return_sequences=True),
        keras.layers.Dense(1, activation="sigmoid"),
    ])



def make_logistic():
    model = keras.Sequential([
        keras.Input(shape=(3,)),
        keras.layers.Lambda(mlp_features),
        keras.layers.Dense(1, activation="sigmoid")
    ])
    return model